#!/bin/sh

set -e

# brew install
if [ ! -f /usr/local/bin/brew]; then
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

# tmux install
if [ ! -f /usr/local/bin/tmux]; then
    brew install tmux 
fi

# vim install
if [ ! -f /usr/local/bin/nvim]; then
    brew install neovim
fi

# fzf install
if [ ! -f /usr/local/bin/fzf]; then
    brew install fzf
fi

if [ ! -d ~/dotfiles]; then
    cd ~
    git clone https://github.com/shuji-takeda/dotfiles.git
fi

brew bundle -v --file=~/dotfiles/Brewfile

if [ ! -d ~/.config ]; then
    mkdir ~/.config
fi

# if [ ! -f /usr/local/bin/yabai]; then
#     brew tap koekeishiya/formulae
#     brew install yabai jq skhd
# fi

# tmux install
if [ ! -f /usr/local/bin/tmux]; then
    brew install tmux 
fi

# vim install
if [ ! -f /usr/local/bin/nvim]; then
    brew install neovim
fi

# yabai & skhd install
# if [ ! -f /usr/local/bin/yabai]; then
#     brew install yabai
# fi
# if [ ! -f /usr/local/bin/skhd]; then
#     brew install skhd
# fi

# starship install
# if [ ! -f /usr/local/bin/starship]; then
#     brew install starship
# fi


# stow -v -d ~/dotfiles/packages -t ~ zsh starship
