#!/bin/sh

set -e

if [ ! -f /usr/local/bin/brew]; then
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

if [ ! -d ~/dotfiles]; then
    cd ~
    git clone https://github.com/shuji-takeda/dotfiles.git
fi

brew bundle -v --file=~/dotfiles/Brewfile

if [ ! -d ~/.config ]; then
    mkdir ~/.config
fi

if [ ! -f /usr/local/bin/yabai]; then
    brew tap koekeishiya/formulae
    brew install yabai jq skhd
fi

stow -v -d ~/dotfiles/packages -t ~ zsh starship